### ISSUE TITLE
User can view empty list of chat rooms

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#1]
## 🖼️ Wireframe

![Empty Chat List](https://user-images.githubusercontent.com/75342275/114103207-8edb4200-987d-11eb-9f82-d19d8963faef.png)

## ✅ Task List

- [x] create a file for chat list
- [x] import react 
- [x] hide new chat form
- [x] define a class for chatsList
- [x] define a render method
- [x] return a react element
- [x] include a header-container
- [x] withing the header container, include and h1 that says "Chats"
- [x] include a plus icon 
- [x] give the header-container a bottom border: 2px solid # dce2ec
- [x] add display flex, and justify content space between to header container
- [x]  add align item flex-end as well
- [x] add a 20px padding to header-container
- [x] Add a container with an empty  ul below header-container
- [x] Add event handle to plus icon that listens for click events
- [x]  create constructor function for ChatList component
- [x] define a methods that handles opening form when icon is clicked. 
- [x] add openForm property to state with an initial value of false
- [x] in openNewChatForm function:
- [x] set openForm property of state to true
- [x] add a logical statement to render method to render form on top of chatlist if openForm property is true.
- [x] add event listener to background over lay of new chat form  
- [x] lift form state to chatList component
- [x] define a handleChange function in chatList component with a parameter that will accept an event target
- [x] add userName and chatName properties to chatlist state
- [x] pass handle change function and state.form.username and state.form.chatName as props to new chat form component
- [x] In the handle change function in new chat form component, call the handle change functions of props and pass them the event target values. 
- [x] set state in chat list component with those values and pass them back in as props
- [x] create a function to handle closing form
- [x] close form when shaded area is clicked
- [x] Check form submission
