### ISSUE TITLE
User can leave a chat room

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#10]
## 🖼️ Wireframe

![Chat Details](https://user-images.githubusercontent.com/75342275/113635650-de273580-9625-11eb-9d5e-a1483793a4ff.png)

## ✅ Task List

- [x] In details app drawer component, render a button 
- [x] give button class name leave-room
- [x] style button
- [x] add onClick property to button
- [x] on click disconnect form socket
- [x] send fetch request to update user's chatRooms in database, and in state
- [x] send fetch request to remove user from members list
- [x] reset hash to return to home page
- [x] check for errors
- [x] remove all console logs
