### ISSUE TITLE
User can create a chat room

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#2]
## 🖼️ Wireframe

![Create chat Modal](https://user-images.githubusercontent.com/75342275/113635028-baafbb00-9624-11eb-8d17-9522ab8ceadb.png)

## ✅ Task List

- [x] Run npm install to install all dependencies and dev dependencies
- [x] create a component module for create chat form
- [x] define a render method that renders form
- [x] add a 'create' tab to form
- [x] style create tab
- [x] give tab an active class that gives it a border bottom
- [x] add an input for chat name
- [x] add an input for user's name
- [x] Adjust input box sizes
- [x] change font size and font weight of input labels
- [x] define a method that handles form submission
- [x] add a chat name property to state
- [x] add a userName property to state
- [x] define a handleChange method
- [x] add handleChange event handler to submit input
- [x] add handleSubmit event handler to form
- [x] on handleChange method, setState's with new input value each time the inputs value changes 
- [x] Create a DB
- [x] initialize client/server
- [x] create a fetch request that sends form input to server
- [x] define route for creating a new room
- [x] destrucutre json object sent from client 
- [x] check socket data to see what info needs to be stored in database 
- [x] in server/index.js define a route for post requests
- [x] create a sql insert statement
- [x] define any params for sql statement
- [x] query db to create chat
- [x] handle any errors
- [x] optimize for desktop view
- [x] check for bugs
- [x] refactor code
