### ISSUE TITLE
User can create a profile

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#29]
## 🖼️ Wireframe

![Create chat Modal](https://user-images.githubusercontent.com/75342275/115094840-db54fc00-9ed3-11eb-981c-f543edd68052.png)

## ✅ Task List

- [x] Create a component called create-user-form
- [x] define a class
- [x] render this component in home.jsx
- [x] in create-user-form component, define a render method.
- [x] create a form 
- [x] style the form
- [x] create db table that holds users
- [x] onSubmit, send users name to server
- [x] create a jwt
- [x] send user's name to db
- [x] on return, save user's info in state in home component. 
- [x] pass user to components via props
- [x] add chats array to user object
- [x] when db is queried for user info, get chats and pass those to chat list.  
- [x] when user creates a chat, append chatRoom to users chatRooms prop
- [x] when app unmounts, update user in db
- [x] when messages are sent, add a sender property. 
- [x] check for errors
- [x] refactor code
