### ISSUE TITLE
User can View Message Area

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#3]
## 🖼️ Wireframe

![Message view](https://user-images.githubusercontent.com/75342275/113635076-d2873f00-9624-11eb-941a-2ba3bada5842.png)

## ✅ Task List

- [x] Create file for message area component
- [x] create a class called messageArea
- [x] define a render method
- [x] Create a header
- [x] in header, include an icon for going back to chat rooms list
- [x]  in header, include Room Name
- [x] in header, include an icon for chat details
- [x] Create a section to hold messages,
- [x] add padding to messages view
- [x] stick text-input at bottom of messages view
- [x] add icon to text-input
- [x] create a text box for typing messages
- [x] Add functionality so message area opens when new chat is created
- [x] add event listener to LI items that can be passed down via props
- [x] onclick, set state with an indicator that chat room should be open and pass 
- [x] Add functionality so message area opens when a chat room is clicked on from initial list
- [x] Go hard as a MF on responsiveness
- [x] adjust font weight for chat room titles
- [x] Fix issue regarding chatroom list getting out of order when page refreshes 
- [x] test for errors + fix errors
- [x] refactor code
