### ISSUE TITLE
User can view chat room ID

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#4]
## 🖼️ Wireframe

![Chat Details](https://user-images.githubusercontent.com/75342275/113635151-f5b1ee80-9624-11eb-8f9b-3604cf0b3c1f.png)

## ✅ Task List

- [x] Create a component for chat details 
- [x] render a section with class name: chat-details
- [x] add an h3 element that displays "Room Id:"
- [x] add a p element and pass that chatRoom id as its value
- [x] add component to home.jsx
- [x] style component
- [x] add an event listener to details icon
- [x] on icon click, add class that slides component into view
- [x] add an x icon to remove view
- [x] checkj for responsiveness
- [x] check for errors
