### ISSUE TITLE
User can view chat rooms from initial chat list

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#5]
## 🖼️ Wireframe
![Chat List](https://user-images.githubusercontent.com/75342275/113635191-07939180-9625-11eb-8560-286cab5bbd58.png)

## ✅ Task List

- [x] Create a new file named chat-room-list-item
- [x] import react
- [x] take response from fetch request and build a render method to make an example list item
- [x] create an endpoint in server for requests set to /api/chatRooms
- [x] create a sql select statement to get rooms from db
- [x] query db
- [x] send response to client
- [x] catch errors 
- [x] store chatRooms in state
- [x] pass chatRooms to ul component via props
- [x] style this item in styles.css
- [x] define a function that stores all list items in an array,
- [x] append the array to the chat lists UL
- [x] create a fetch request to get all chat rooms from data base.
- [x] take response and and create an li for each chatroom
- [x] test by creating multiple group chats 
- [x] make responsive
- [x] refactor code. 
- [x] check for errors, 
- [x] handle any errors
