### ISSUE TITLE
User can join an existing chat room

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#6]
## 🖼️ Wireframe

![Join Chat List](https://user-images.githubusercontent.com/75342275/113635270-2f82f500-9625-11eb-87c9-c04689b267b0.png)

## ✅ Task List

- [x] Add Tab to new-chat-form component
- [x] on submit query db for chat rooms,
- [x] add chatroom id to users profile
- [x] render chat on screen
- [x] when chat room is clicked 
- [x] socket.join that room
- [x] check for errors
