### ISSUE TITLE
User can send a message

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#7]
## 🖼️ Wireframe

![Send message](https://user-images.githubusercontent.com/75342275/113635302-3d387a80-9625-11eb-9205-cecfee7f53ac.png)

![Joined Chat](https://user-images.githubusercontent.com/75342275/114794377-386c7880-9d41-11eb-8e88-5e5f01884106.png)

## ✅ Task List

- [x] add a sendMessage property to state in message area.
- [x] define a function that grabs users input and sets state with the new value
- [x] pass that function to textarea via props
- [x] in text area's on change function, call this.props.passedFunction and pass the textarea's value as an argument. 
- [x] ensure message is saved in state.
- [x] add an event listener to send icon
- [x] listen for click event
- [x] onclick:
- [x] call a fucntion named sendmessage.
- [x] grab input value
- [x] create an init object 
- [x] send a fetch request with init object
- [x] store the messages in db maybe in their own table and chatId to link messages with their rooms?
- [x] add table to db name messages
- [x] in my /api/chat route, query db to. insert message into db
- [x] call emit method on the return of the to method being called on io object
- [x] on send icon click, reset text box. 
- [x] append message to screen
- [x] create a component call Messages
- [x] pass room messages in state to Messages component. 
- [x] Render a list that contains  sent message
- [x] give sent message a class name
- [x] style component
- [x] make responsive
- [x] check for errors
