### ISSUE TITLE
User can receive a message

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#8]
## 🖼️ Wireframe

![Message-dialogue](https://user-images.githubusercontent.com/75342275/113635382-59d4b280-9625-11eb-82f5-69289eaaa1cf.png)
![Messages](https://user-images.githubusercontent.com/75342275/113635890-52fa6f80-9626-11eb-8b9f-7a910c9aeac0.png)

## ✅ Task List

- [x] Add an h3 to message blimp that will contain users name
- [x] pass sender prop to this h3
- [x] create a class in styles.css for messages sent by a different user
- [x] add a condition that assigns a class to message based on sender
- [x] check for errors
- [x] make responsive
- [x] refactor code
