### ISSUE TITLE
User can view chat room members

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/App-Chat#9]
## 🖼️ Wireframe

![Chat Details](https://user-images.githubusercontent.com/75342275/113635417-71ac3680-9625-11eb-8927-6baa95089c92.png)

## ✅ Task List

- [x] Add an h3 to detail drawer component.
- [x] below, create a ul that renders all chat member
- [x] add a column to db that records members. 
- [x] when a user joins a chatRoom, append the user's userName to array in db column
- [x] when room is opened, create a function that displays list of uasers
- [x] style elements 
- [x] check for errors
- [x] fix bug that records a null chatRoom in users table when a user is created
- [x] refactor code
